name:                haskell-http
version:             0.1.0.0
github:              "Github username here/haskell-http"
license:             MIT
author:              "Author name here"
maintainer:          "Author email here"
copyright:           "2019 Author name here"
# synopsis: A new project for TDD with Haskell.
# description: haskell-http see README.md for further details.
# category: Other

extra-source-files:
  - README.md
  - package.yaml
  - LICENSE.md

ghc-options: -Wall

dependencies:
  - base >= 4.7 && < 5
  - aeson
  - http-client
  - http-conduit
  - http-types
  - text

library:
  source-dirs: src

executables:
  chuck:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - haskell-http

tests:
  haskell-http-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - haskell-http
      - hspec
      - QuickCheck
